name: My First Workflow

on: push  

jobS: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Adding checkpout
          uses: actions/checkout@v6
          
        - name: Welcome to GHU
          run: echo "welcome to Workflow"
        
        - name: Show the Files
          run: ls

        - name: Read Files  
          run: cat RRADME.md
          