name: Generating ASCII

on: push

jobs: 
    ascii_jobs:
        runs-on: ubuntu-latest
        steps:
        - name: Adding Checkout to repo
          uses: actions/checkout@v6
          
        - name: installing cowsay program
          run: sudo apt-get install cowsay -y

        - name: Generat ASCII Artwork
          run: cowsay -f sheep "Run for cover, I am a sheep....RAWR">> sheep.txt

        - name: Test File Exist
          run: grep -i "sheep" sheep.txt

        - name: read the file
          run: cat sheep.txt

        - name: list Repo file
          run: ls -ltra

