name: Matrix congiration
on: 
  push:
  workflow_dispatch:
jobs:
    deploye-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Docker Details
      run: docker info
    - name: Run Image 
      run: docker run hello world 

    deploye-on-windows:
    runs-on: windows
    steps:
    - name: Echo Docker Details
      run: docker info
    - name: Run Image 
      run: docker run hello world
